### PR TITLE
- Added Bootstrap info to README.md

### PR DESCRIPTION
**Pull request by LondonTran**
Participating in Hacktoberfest :)

### CODE REVIEW

**Review by bineetNaidu — APPROVED** [review]
Good Resources ADDED.

**Comment by LondonTran** [comment]
Can you please label with "hacktoberfest-accepted"?

**Comment by bineetNaidu** [comment]
> Can you please label with "hacktoberfest-accepted"?

Iam Not the Owner of this repo. Please ask the owner.

**Review by saurabhnative — APPROVED** [review]

**Comment by codeclassifiers** [comment]
@all-contributors please add @LondonTran for updating docs

**Comment by LondonTran** [comment]
Thank you!

**Pull request merged**
